# sstart MCP Demo - MongoDB with OpenBao + Template Provider
inherit: true

providers:
  # Fetch MongoDB credentials from OpenBao
  # Secrets are fetched with their original names
  - kind: vault
    id: mongodb_creds
    address: http://localhost:8200
    token: demo-token
    path: mongodb

  # Construct MongoDB connection string from components
  - kind: template
    uses:
      - mongodb_creds
    templates:
      MDB_MCP_CONNECTION_STRING: "mongodb://{{.mongodb_creds.username}}:{{.mongodb_creds.password}}@{{.mongodb_creds.host}}:{{.mongodb_creds.port}}/{{.mongodb_creds.database}}?authSource={{.mongodb_creds.auth_database}}"

# Enable caching (recommended for MCP proxy)
cache:
  enabled: true
  ttl: 15m

# MCP server configuration
mcp:
  servers:
    # MongoDB MCP server
    - id: mongodb
      command: docker
      args:
        - run
        - --rm
        - -i
        - --network=host
        - -e
        - MDB_MCP_CONNECTION_STRING
        - mcp/mongodb:latest
